const carbonFootprint = document.querySelector("h2");
const householdMembers = 6;
const homeSize = 4;
const foodChoices = 8;
const waterConsumption = 5;
const householdPurchases = 4;
const garbageCans = 20;
const wasteRecycle = 8;
const annualTransportation = 6;
const environmentalImpact = householdMembers + homeSize + foodChoices + waterConsumption + householdPurchases + garbageCans + wasteRecycle + annualTransportation;
console.log(environmentalImpact);
carbonFootprint.textContent = environmentalImpact;